server:
  port: 19106

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: ws
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
