server:
  port: 19094

spring:
  application:
    name: user-service
  data:
    redis:
      host: localhost
      port: 6379
      password: '0000'
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: '0000'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: never