server:
  port: 19094

spring:
  application:
    name: user-service
  data:
    redis:
      host: ${REDIS_URL}
      port: 6379
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://server:19090/eureka/
