server:
  port: 19094

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: users #기본 스키마 지정
        format_sql: true
        highlight_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:19090/eureka/
