version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: haot-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - how-about-over-there_msa-network

  grafana:
    image: grafana/grafana:latest
    container_name: haot-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - how-about-over-there_msa-network

volumes:
  grafana-data:

networks:
  how-about-over-there_msa-network:
    external: true  # 이미 생성된 네트워크를 사용