version: '3.7'

services:
  eureka-service:
    image: haot-ecr/server:latest
    container_name: eureka-service
    ports:
      - "19090:19090"
    networks:
      - msa-network
  gateway-service:
    image: haot-ecr/gateway:latest
    container_name: gateway-service
    ports:
      - "19091:19091"
    depends_on:
      - eureka-service
    networks:
      - msa-network
  auth-service:
    image: haot-ecr/auth:latest
    container_name: auth-service
    ports:
      - "19092:19092"
    depends_on:
      - eureka-service
      - gateway-service
    networks:
      - msa-network
  #user
  user-service:
    image: haot-ecr/user:latest
    container_name: user-service
    ports:
      - "19094:19094"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - eureka-service
      - gateway-service
    networks:
      - msa-network
  #coupons
  coupon-service:
    image: haot-ecr/coupon:latest
    container_name: coupon-service
    ports:
      - "19096:19096"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - eureka-service
      - gateway-service
    networks:
      - msa-network
  #lodge
  lodge-service:
    image: haot-ecr/lodge:latest
    container_name: lodge-service
    ports:
      - "19098:19098"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - eureka-service
      - gateway-service
    networks:
      - msa-network
  #payment
  payment-service:
    image: haot-ecr/payment:latest
    container_name: payment-service
    ports:
      - "19102:19102"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - eureka-service
      - gateway-service
    networks:
      - msa-network
  #point
  point-service:
    image: haot-ecr/point:latest
    container_name: point-service
    ports:
      - "19104:19104"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - eureka-service
      - gateway-service
    networks:
      - msa-network
  #reservation
  reservation-service:
    image: haot-ecr/reservation:latest
    container_name: reservation-service
    ports:
      - "19100:19100"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - eureka-service
      - gateway-service
    networks:
      - msa-network
  #review
  review-service:
    image: haot-ecr/review:latest
    container_name: review-service
    ports:
      - "19106:19106"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - eureka-service
      - gateway-service
    networks:
      - msa-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: haot-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
    networks:
      - msa-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: haot-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - msa-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: haot-kafka-ui
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - msa-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: haot-zipkin
    ports:
      - "9411:9411"
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge