spring:
  application:
    name: eureka-server

server:
  port: 19090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${SERVER_DNS}/eureka/
  instance:
    hostname: ${SERVER_HOST}