global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'haot-prometheus'
    static_configs:
      - targets: ['haot-prometheus:9090']

  - job_name: 'haot-grafana'
    static_configs:
      - targets: ['haot-grafana:3000']

  - job_name: 'haot-kafka'
    static_configs:
      - targets: [ 'haot-kafka-exporter:9308' ]

  - job_name: 'haot-redis'
    static_configs:
      - targets: [ 'haot-redis-exporter:9121' ]

  - job_name: 'coupon-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'coupon-service:19096' ]