server:
  port: 19092

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

jwt:
  secret:
    key: W3JwO3COO+XEYBKoVl3VNMfehUaEOnKWL48J+bqsOII8jSehu/sSO3GGrwyKxQyQHBNCUAJMmWldSA6Dyo7azA==

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: never