server:
  port: 19092

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://${SERVER_DNS}/eureka/

jwt:
  secret:
    key: W3JwO3COO+XEYBKoVl3VNMfehUaEOnKWL48J+bqsOII8jSehu/sSO3GGrwyKxQyQHBNCUAJMmWldSA6Dyo7azA==