server:
  port: 19100

spring:
  application:
    name: reservation-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

eureka:
  instance:
    hostname: ${RESERVATION_SERVICE_HOST}
  client:
    service-url:
      defaultZone: http://${SERVER_DNS}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: never

gateway:
  url: http://${GATEWAY_SERVICE_HOST}:19091