server:
  port: 19104
spring:
  application:
    name: point-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/how_about_over_there
    username:
    password:
  data:
    redis:
      port:
      host:
      username:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
logging:
  level:
    org.springframework.cache: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: never